[NOD-1575] Implement Clone and Equal for all model types (DO NOT MERGE)
kaspanet/kaspad pull request #1155
Opened 2020-11-26 11:16 UTC by someone235

2020-11-26 12:39 UTC, oudeis commented
Rebuild after update in master

2020-11-26 12:46 UTC, stasatdaglabs requested changes

2020-11-26 12:46 UTC, stasatdaglabs commented on domain/consensus/model/externalapi/blockinfo.go
> +	if bi == nil {
Please remove this condition since cloning a nil is always a bug.

2020-11-26 12:46 UTC, stasatdaglabs commented on domain/consensus/model/externalapi/coinbase.go
> +	if dcd == nil {
Please remove this check.

2020-11-26 12:46 UTC, stasatdaglabs commented on domain/consensus/model/externalapi/hash.go
> +var _ = [DomainHashSize]byte{}
Why would this ever not compile?

2020-11-26 12:46 UTC, stasatdaglabs commented on domain/consensus/model/externalapi/subnetworkid.go
> +var _ = [DomainSubnetworkIDSize]byte{}
Why would this ever not compile?

2020-11-26 12:46 UTC, stasatdaglabs commented on domain/consensus/model/externalapi/sync.go
> +	if si == nil {
Please remove this check.

2020-11-26 12:46 UTC, stasatdaglabs commented on domain/consensus/model/externalapi/sync.go
> +func (s SyncState) Clone() SyncState {
This file appears to be missing a compilation check and Equal.

2020-11-26 12:46 UTC, stasatdaglabs commented on domain/consensus/model/externalapi/transaction.go
> +	for i, input := range tx.Inputs {
Please also make sure that the lengths are equal.

2020-11-26 12:46 UTC, stasatdaglabs commented on domain/consensus/model/externalapi/transaction.go
> +	for i, output := range tx.Outputs {
Please also make sure that the lengths are equal.

2020-11-26 13:33 UTC, stasatdaglabs requested changes

2020-11-26 13:33 UTC, stasatdaglabs commented on domain/consensus/model/acceptancedata.go
> +	for i, acceptanceData := range bad.TransactionAcceptanceData {
Please make sure the lengths are equal.

2020-11-26 13:59 UTC, stasatdaglabs submitted a review, later dismissed

2020-12-22 15:21 UTC, stasatdaglabs commented
Rebuild after update in master

2020-12-22 15:38 UTC, stasatdaglabs approved these changes

2020-12-22 15:38 UTC, merged