Replace blue score with blue work in ghostdag
kaspanet/kaspad pull request #1172
Opened 2020-12-01 15:16 UTC by elichai

Resolves #1021
More details in the #1021 issue.

This still works like blueScore by: 
1. Inheriting the Blue Work of the SelectedParent.
2. Add to that the Sum of the *Work* of all the blue merge set.

Note that blue work and work are 2 separate things.
blueWork is the sum of all the work of all the blue blocks in the past of a block.
Work is just the work a single block did (`util.CalcWork(block.Bits)`)

Also note that just like with blueScore, the SelectedParent is part of the blue merge set, meaning that you also add the work of the selected parent when you sum the work of the blue merge set.

2020-12-03 12:00 UTC, elichai commented
@svarogg I want to note that this will probably affect performance, probably for the worse. but I hope not too much (especially now that the work will always be a single word anyway)

2020-12-06 11:49 UTC, someone235 requested changes

2020-12-06 11:49 UTC, someone235 commented on domain/consensus/database/serialization/dbobjects.pb.go
> +// 	protoc        v3.12.4
Please don't change the protoc version

2020-12-06 11:49 UTC, someone235 commented on domain/consensus/processes/ghostdagmanager/ghostdag.go
> +		// Then we add up all the *work*(not blueWork) that all our blues and selected parent did
all our blues -> all of new block merge set blues

2020-12-06 12:18 UTC, elichai commented
Rebased

2020-12-06 12:28 UTC, someone235 submitted a review, later dismissed

2020-12-06 12:33 UTC, someone235 approved these changes

2020-12-06 12:45 UTC, merged