Allow to configure consensus (closes #1067)
kaspanet/kaspad pull request #1175
Opened 2020-12-02 14:52 UTC by someone235

2020-12-02 14:54 UTC, elichai commented
Can you give an example of how to configure everything?
Thanks!

2020-12-02 15:09 UTC, someone235 commented
> Can you give an example of how to configure everything?
> Thanks!

`kaspad --devnet --override-dag-params-file=/tmp/x.json`

and this is an example JSON file

`{"targetTimePerBlockInMilliSeconds":1,"powMax":"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"}`

The full JSON definition can be found [here](https://github.com/kaspanet/kaspad/pull/1175/files#diff-ea73f239d8f12ff284184f15ac2f691b597a74cede1db17c8ebbb8fdb7c162b3R26)

2020-12-02 16:07 UTC, svarogg requested changes

2020-12-02 16:07 UTC, svarogg commented on domain/dagconfig/params.go
> +	maxCoinbasePayloadLength = 150
I think we still want these in constants, and use the default Params out of constants

2020-12-02 16:11 UTC, someone235 commented on app/protocol/flows/blockrelay/handle_relay_invs.go
> -			blueScore, err := blocks.ExtractBlueScore(block)
It's gonna be changed anyway by Stas's code

2020-12-03 16:28 UTC, svarogg approved these changes

2020-12-03 16:30 UTC, merged