[NOD-1548] Re-add test difficulty + Make GHOSTDAGData immutable + don't clone in store
kaspanet/kaspad pull request #1178
Opened 2020-12-03 13:14 UTC by svarogg

2020-12-03 15:57 UTC, someone235 requested changes

2020-12-03 15:57 UTC, someone235 commented on domain/consensus/processes/ghostdagmanager/ghostdag_test.go
> +						factory.implName, info.Name(), testBlockData.ID, testBlockData.SelectedParent, string(ghostdagData.SelectedParent()[:]))
hash has a stringer, so you don't need to convert it to string (and this way it's also not reversed)

2020-12-03 16:31 UTC, someone235 approved these changes

2020-12-06 10:13 UTC, someone235 approved these changes

2020-12-06 10:30 UTC, svarogg commented
Rebuild after update in master

2020-12-06 10:35 UTC, merged