comments on default constants
kaspanet/kaspad pull request #1253
Opened 2020-12-21 11:27 UTC by FestinaLente666

Added comments on consensus constant defaults

2020-12-21 12:19 UTC, svarogg requested changes

2020-12-21 12:19 UTC, svarogg commented on domain/dagconfig/consensus_defaults.go
> +	// such blocks are delayed.
We currently don't delay blocks. We reject them without marking as invalid instead.

2020-12-21 12:19 UTC, svarogg commented on domain/dagconfig/consensus_defaults.go
> +	// The pruning block is selected similary, with the following duration:
typo: selected similar**l**y

2020-12-21 12:19 UTC, svarogg commented on domain/dagconfig/consensus_defaults.go
> +	//					2*defaultFinalityDuration/defaultTargetTimePerBlock + 4*defaultMergeSetSizeLimit*defaultGHOSTDAGK +
Please decrease the tabs so that this fits in a single line

2020-12-21 12:19 UTC, svarogg commented on domain/dagconfig/consensus_defaults.go
> +	// Should be parametrized such that the average width of the DAG is about defaultMaxBlockParents and such that most of the
typo: paramet**e**rized

2020-12-21 16:20 UTC, FestinaLente666 commented on domain/dagconfig/consensus_defaults.go
> +	// defaultMaxBlockSize is a bound on the size of a block in bytes, larger values increase the bound d
Done

2020-12-22 08:50 UTC, svarogg requested changes

2020-12-22 08:50 UTC, svarogg commented on domain/dagconfig/consensus_defaults.go
> +//			defaultGHOSTDAGK
This looks like some sort of typo or I dunno what.

2020-12-22 08:50 UTC, svarogg commented on domain/dagconfig/consensus_defaults.go
> +	//		pruning block duration =
I'd remove another tab from this and next line, so that it actually fits inside the github source view.

2020-12-22 09:44 UTC, svarogg approved these changes

2020-12-22 09:44 UTC, merged