Red inclusion
kaspanet/kaspad pull request #1275
Opened 2020-12-23 13:39 UTC by someone235

Closes #1029

2020-12-23 13:53 UTC, elichai commented
Does this include https://github.com/kaspanet/kaspad/issues/1259 or is it separate?

2020-12-24 09:20 UTC, someone235 commented
> Does this include #1259 or is it separate?

Yeah sorry for not mentioning it. For now red block reward and fees are dismissed. I opened an issue to fix it #1276

2020-12-24 10:34 UTC, stasatdaglabs requested changes

2020-12-24 10:34 UTC, stasatdaglabs commented on app/protocol/flows/blockrelay/ibd.go
> +func (flow *handleRelayInvsFlow) fetchUTXOSetIfMissing() (bool, error) { // TODO: Remove this
By chance, did you mean to remove this?

2020-12-24 10:34 UTC, stasatdaglabs commented on go.mod
> +	github.com/go-test/deep v1.0.7
Please remove this dependency and run `go mod tidy`

2020-12-24 10:34 UTC, stasatdaglabs commented on domain/consensus/processes/consensusstatemanager/resolve_block_status_test.go
> +// red blocks transactions, and that the block reward is payed only for blue blocks.
Typo: payed -> paid

2020-12-24 10:34 UTC, stasatdaglabs commented on domain/consensus/processes/consensusstatemanager/resolve_block_status_test.go
> +		tc, teardown, err := factory.NewTestConsensus(params, "TestTransactionAcceptance")
Please don't use two-letter abbreviations.

2020-12-24 10:34 UTC, stasatdaglabs commented on domain/consensus/processes/consensusstatemanager/resolve_block_status_test.go
> +		// Generate fundingBlock3 to pay for fundingBlock1 and fundingBlock2
fundingBlock3 funds fundingBlock2 only. Please correct this comment.

2020-12-24 16:02 UTC, stasatdaglabs approved these changes

2020-12-24 16:12 UTC, merged