Upgradability mechanisms script version
kaspanet/kaspad pull request #1313
Opened 2020-12-29 08:42 UTC by talelbaz

Changes type of block version, txn version, and scriptPublicKey version to uint16.
Also, changes the tests to suit.

2021-01-04 14:50 UTC, stasatdaglabs requested changes

2021-01-04 14:50 UTC, stasatdaglabs commented on go.mod
> +	github.com/golang/protobuf v1.4.3
Please revert this.

2021-01-04 14:50 UTC, stasatdaglabs commented on infrastructure/network/netadapter/server/grpcserver/protowire/messages.proto
> +message RpcScriptPubKey {
Please rename this to RpcScriptPublicKey.

2021-01-04 14:50 UTC, stasatdaglabs commented on infrastructure/network/netadapter/server/grpcserver/protowire/messages.proto
> +  string scriptPubKey = 2;
Please rename this to scriptPublicKey.

2021-01-04 14:50 UTC, stasatdaglabs commented on infrastructure/network/netadapter/server/grpcserver/protowire/messages.proto
> +  RpcScriptPubKey scriptPubKey = 2;
Please rename this to scriptPublicKey.

2021-01-04 14:50 UTC, stasatdaglabs commented on infrastructure/network/netadapter/server/grpcserver/protowire/messages.proto
> +  RpcScriptPubKey scriptPubKey = 2;
Please rename this to RpcScriptPublicKey.

2021-01-04 14:50 UTC, stasatdaglabs commented on testing/integration/utxo_index_test.go
> +		if notificationEntry.UTXOEntry.Amount != foundResponseEntry.UTXOEntry.Amount {
Please utxo UTXOEntry.Equal instead.

2021-01-05 13:27 UTC, stasatdaglabs commented
Rebuild after update in master

2021-01-05 13:42 UTC, someone235 requested changes

2021-01-05 13:42 UTC, someone235 commented on app/rpc/rpccontext/verbosedata.go
> +		disbuf, _ := txscript.DisasmString(constants.ScriptPublicKeyVersion, transactionInput.SignatureScript)
Change to MaxScriptPublicKeyVersion

2021-01-05 13:42 UTC, someone235 commented on domain/consensus/utils/constants/constants.go
> +	TransactionVersion uint16 = 0
Add Max

2021-01-05 13:42 UTC, someone235 commented on domain/consensus/utils/constants/constants.go
> +	BlockVersion uint16 = 0
Add Max

2021-01-05 13:42 UTC, someone235 commented on domain/consensus/utils/txscript/sign.go
> +		signedScriptPublicKey := &externalapi.ScriptPublicKey{
Rename to scriptHashPreimageScriptPublicKey

2021-01-05 13:42 UTC, someone235 commented on domain/consensus/utils/txscript/standard_test.go
> +		expectedScript := mustParseShortForm(test.expectedScript)
`mustParseShortForm` should also get version

2021-01-05 14:56 UTC, stasatdaglabs approved these changes

2021-01-05 15:12 UTC, someone235 approved these changes

2021-01-05 15:18 UTC, stasatdaglabs commented
Rebuild after update in master

2021-01-05 15:50 UTC, merged