Add TestCheckParentBlockBodiesExist
kaspanet/kaspad pull request #1405
Opened 2021-01-12 16:34 UTC by someone235

2021-01-12 16:37 UTC, elichai commented on domain/consensus/processes/blockbuilder/test_block_builder.go
> +	header, err := bb.buildUTXOInvalidHeader(parentHashes, genesisTransactions)
That's quite confusing.
```
BuildUTXOInvalidHeader -> BuildUTXOInvalidBlock -> buildUTXOInvalidHeader
```

2021-01-13 12:00 UTC, elichai commented on domain/consensus/processes/blockvalidator/block_body_in_context_test.go
> +	})
Isn't that a duplicate block though? because you added it to consensus in L44

2021-01-14 09:05 UTC, svarogg requested changes

2021-01-14 11:13 UTC, elichai approved these changes

2021-01-14 11:16 UTC, elichai approved these changes

2021-01-14 11:31 UTC, svarogg approved these changes

2021-01-14 11:31 UTC, merged