Add TestIBDWithPruning
kaspanet/kaspad pull request #1425
Opened 2021-01-17 15:56 UTC by someone235

2021-01-18 07:10 UTC, svarogg requested changes
Please add some validations:
1. Before starting netsync: Make sure syncer pruning point is expected point, and syncee pruning point is genesis.
2. After netsync done: Make sure syncee pruning point is syncer's point, and that blocks under it are pruned.

2021-01-18 08:59 UTC, svarogg submitted a review, later dismissed

2021-01-18 11:40 UTC, elichai commented
+3.5% coverage Nice :)

2021-01-20 08:02 UTC, svarogg approved these changes

2021-01-20 08:07 UTC, merged