Ban by IP
kaspanet/kaspad pull request #1471
Opened 2021-01-31 16:11 UTC by someone235

Fixes #1380

2021-01-31 16:19 UTC, someone235 commented
Fixes #1053

2021-02-01 07:35 UTC, stasatdaglabs requested changes

2021-02-01 07:35 UTC, stasatdaglabs commented on domain/consensus/processes/blockvalidator/block_header_in_context.go
> +				panic(err)
Instead of panicking, populate an error variable outside of the closure and check it afterwards.

2021-02-01 07:35 UTC, stasatdaglabs commented on infrastructure/network/connmanager/outgoing_connections.go
> -			c.addressManager.RemoveAddress(netAddress)
If you don't remove the address here, doesn't it mean that we keep all addresses indefinitely?

2021-02-01 07:35 UTC, stasatdaglabs commented on infrastructure/network/addressmanager/addressmanager.go
> +	delete(am.bannedAddresses, key.address)
Banned addresses should remain banned until they are unbanned. Please remove this line.

2021-02-01 08:51 UTC, stasatdaglabs approved these changes

2021-02-01 08:51 UTC, merged