Tests validateDifficulty ( ValidatePruningPointViolationAndProofOfWorkAndDifficulty)
kaspanet/kaspad pull request #1532
Opened 2021-02-16 13:36 UTC by talelbaz

part of #1314 
(and also part of #1008)
Adds tests for validateDifficulty on ValidatePruningPointViolationAndProofOfWorkAndDifficulty.go

2021-02-17 15:19 UTC, someone235 requested changes

2021-02-17 15:19 UTC, someone235 commented on domain/consensus/processes/blockvalidator/pruning_violation_proof_of_work_and_difficulty_test.go
> +		tc, teardown, err := factory.NewTestConsensus(params, false, "TestCheckPruningPointViolation")
Please fix TestCheckPruningPointViolation->TestValidateDifficulty

2021-02-17 15:19 UTC, someone235 commented on domain/consensus/processes/blockvalidator/pruning_violation_proof_of_work_and_difficulty_test.go
> +func TestValidateDifficulty(t *testing.T) {
Can you please add a comment that explains what the test does?

2021-02-18 10:32 UTC, elichai commented on domain/consensus/processes/blockvalidator/pruning_violation_proof_of_work_and_difficulty_test.go
> +}
Why is this needed?

2021-02-21 14:08 UTC, elichai submitted a review, later dismissed

2021-02-21 14:15 UTC, someone235 requested changes

2021-02-21 14:15 UTC, someone235 commented on domain/consensus/processes/blockvalidator/pruning_violation_proof_of_work_and_difficulty_test.go
> +// TestValidateDifficulty verified that in case of a block with an unexpected difficulty,
verified->verifies

2021-02-21 14:15 UTC, someone235 commented on domain/consensus/processes/blockvalidator/pruning_violation_proof_of_work_and_difficulty_test.go
> +// function ValidatePruningPointViolationAndProofOfWorkAndDifficulty. The require difficulty is
require->required

2021-02-21 14:36 UTC, someone235 approved these changes

2021-02-21 15:00 UTC, merged