Add consensus.Config as a wrapper for dagParams
kaspanet/kaspad pull request #1680
Opened 2021-04-18 12:49 UTC by elichai

This is a follow up built on #1679 it wrapps `isArchivalNode` and `EnableSanityCheckPruningUTXO` in a struct that also wraps `dagParams`

2021-04-18 14:02 UTC, svarogg requested changes

2021-04-18 14:09 UTC, elichai commented on domain/consensus/finality_test.go
> +package consensus_test
I do because these tests depends on `testutils` which now depends on `consensus` so these tests are causing a dependency cycle

2021-04-18 14:39 UTC, svarogg submitted a review, later dismissed

2021-04-18 14:40 UTC, svarogg commented
Approved. Waiting on #1679 for merge

2021-04-19 06:07 UTC, svarogg approved these changes

2021-04-19 06:07 UTC, merged