Tests for lock time - CLTV (conditioned by time and block height)
kaspanet/kaspad pull request #1733
Opened 2021-05-30 10:14 UTC by talelbaz

The first part of #1257 
Tests for lock time - CLTV (conditioned by time and block height).
The second part of #1257 will include tests for CSV and will be in a separate pull request.

2021-06-10 13:10 UTC, someone235 requested changes

2021-06-10 13:10 UTC, someone235 commented on domain/consensus/timelock_CLTV_test.go
> +			tipHash, _, err = testConsensus.AddBlock([]*externalapi.DomainHash{tipHash}, nil, nil)
You can also stop when the DAA score of the tip equals to the target, instead of keeping track of currentBlockHeight

2021-06-10 13:10 UTC, someone235 commented on domain/consensus/timelock_CLTV_test.go
> +			[]*externalapi.DomainTransaction{transactionThatSpentTheLockedOutput})
Please also try to spend the output with a transaction with wrong locktime

2021-06-10 13:10 UTC, someone235 commented on domain/consensus/timelock_CLTV_test.go
> +// the time is reached to the set target (compared to the past median time)).
is -> has

2021-06-10 13:10 UTC, someone235 commented on domain/consensus/timelock_CLTV_test.go
> +// the time is reached to the set target (compared to the past median time)).
"median time))" -> "median time)"

2021-06-10 13:10 UTC, someone235 commented on domain/consensus/timelock_CLTV_test.go
> +		// Add a block that contains a transaction that tries to spend the locked output before the time, and therefore should be failed.
Please also try to spend the output with a transaction with wrong locktime

2021-06-14 11:06 UTC, talelbaz commented on domain/consensus/timelock_CLTV_test.go
> +		currentBlockHeight++
Delete the currentBlockHeight variable.

2021-06-14 11:42 UTC, talelbaz commented on domain/consensus/timelock_CLTV_test.go
> +		fundingTransaction, err := testutils.CreateTransaction(blockC.Transactions[transactionhelper.CoinbaseTransactionIndex], fees)
Removed

2021-06-16 14:55 UTC, closed without merging