Modify locktime thresholds to accomodate 64 bits and millisecond timestamps
kaspanet/kaspad pull request #1770
Opened 2021-06-29 12:49 UTC by svarogg

2021-06-29 14:21 UTC, someone235 requested changes

2021-06-29 14:21 UTC, someone235 commented on domain/consensus/utils/txscript/scriptnum_test.go
> +		// Values above 8 bytes should be always
should be always what?

2021-06-30 06:53 UTC, svarogg commented on domain/consensus/utils/txscript/opcode.go
> +		paddedSequenceBytes := make([]byte, 8)
Do we want to enforce minimal encoding in sequence locks?
I think sequence locks are naturally malleable(move the lock 1 second, play with the inactive bits, etc.), I don't think there's a point enforcing minimal encoding with them.

2021-06-30 07:57 UTC, someone235 approved these changes

2021-06-30 07:57 UTC, merged