Use separate than finality depth for merge set calculations after HF
kaspanet/kaspad pull request #2013
Opened 2022-04-07 20:23 UTC by someone235

2022-04-10 11:38 UTC, michaelsutton requested changes

2022-04-10 11:38 UTC, michaelsutton commented on app/protocol/flows/v5/blockrelay/ibd.go
> +	// Note: we don't wait until the hard fork is activated before applying these rules in the p2p leve.
leve -> level

2022-04-10 11:38 UTC, michaelsutton commented on app/protocol/flows/v5/blockrelay/ibd.go
> +	highestSharedChainBlock, found, err := flow.Domain().Consensus().HighestChainBlockInPastOf(highestKnownSyncerChainHash)
`highestSharedChainBlock` sounds like it is the chain block on both sides. Perhaps rename to `highestChainBlockInSyncerPast`

2022-04-10 11:38 UTC, michaelsutton commented on app/protocol/flows/v5/blockrelay/ibd.go
> +	virtualSelectedParent, err := flow.Domain().Consensus().GetVirtualSelectedParent()
Isn't it better practice to extract `flow.Domain().Consensus()` to a local variable to use in all calls ?

2022-04-10 11:38 UTC, michaelsutton commented on domain/consensus/consensus.go
> +		blockLocator, err := s.syncManager.CreateHeadersSelectedChainBlockLocator(stagingArea, lowHash, highHash)
The code might be simpler if we directly implement a binary search here w/o going through block locator logic (also makes it `log(n)` over `(log(n))^2`). Though I can see why reusing has benefits.

2022-04-10 21:06 UTC, someone235 commented on domain/consensus/processes/mergedepthmanager/merge_depth_manager.go
> +		notViolatingFinality, err := mdm.dagTopologyManager.IsInSelectedParentChainOf(stagingArea, mergeDepthRoot, blue)
Rename this var

2022-04-11 21:12 UTC, michaelsutton approved these changes

2022-04-11 21:17 UTC, michaelsutton approved these changes

2022-04-11 21:26 UTC, merged