Change the way the miner executable reports execution errors (closes issue #1677)
kaspanet/kaspad pull request #2048
Opened 2022-05-12 00:26 UTC by Aleoami

2022-05-17 09:53 UTC, svarogg requested changes

2022-05-17 09:53 UTC, svarogg commented on cmd/kaspaminer/main.go
> +		printErrorAndExit(fmt.Errorf("Error connecting to the RPC server: %s", err))
Please use errors.Errorf instead (in all cases)

2022-05-18 18:09 UTC, Aleoami reviewed
Done

2022-05-18 18:15 UTC, Aleoami reviewed
fixed import

2022-05-22 06:29 UTC, svarogg approved these changes

2022-06-03 16:20 UTC, someone235 requested changes

2022-06-03 16:20 UTC, someone235 commented on cmd/kaspaminer/main.go
> +		printErrorAndExit(errors.Errorf("Error connecting to the RPC server: %s", err))
This will lose the error stack information

2022-06-03 16:20 UTC, someone235 commented on cmd/kaspaminer/main.go
> +			printErrorAndExit(errors.Errorf("Error in mine loop: %s", err))
This will lose the error stack information

2022-06-15 11:05 UTC, merged