[NOD-1414] Write domain interfaces and stub implementations for the new kaspadstate architecture
kaspanet/kaspad pull request #941
Opened 2020-09-30 10:35 UTC by stasatdaglabs

2020-10-01 09:26 UTC, svarogg requested changes

2020-10-01 09:26 UTC, svarogg commented on domain/kaspadstate/algorithms/interfaces.go
> +	SerializedUTXOSet() []byte
Should move to pruning

2020-10-01 09:26 UTC, svarogg commented on domain/kaspadstate/algorithms/interfaces.go
> +	Children(blockHash *daghash.Hash) []*daghash.Hash
Children misses from UML. Other methods  have different signatures in UML

2020-10-01 09:26 UTC, svarogg commented on domain/kaspadstate/algorithms/interfaces.go
> +	FindPruningPoint(blockHash *daghash.Hash) *daghash.Hash
Should be modified as discusses

2020-10-01 09:26 UTC, svarogg commented on domain/kaspadstate/algorithms/interfaces.go
> +	IsInPastOf(blockHashA *daghash.Hash, blockHashB *daghash.Hash) bool
Rename: IsInPast ->  IsReachableFrom
Add: IsReachabilityTreeAncestorOf
Make DAGTopology use those for isInPast/isInSelectedParentChain. Update dependancies accordingly

2020-10-01 09:26 UTC, svarogg commented on domain/kaspadstate/model/readonlyutxoset.go
> +type ReadOnlyUTXOSet interface {
We should decide what's the API of ReadOnlyUTXOSet, SelectedParentIterator, etc.

Someone is going to implement those. Someone else is going to use those.
Therefore APIs should be ready ahead of time.

2020-10-04 06:21 UTC, someone235 requested changes

2020-10-04 10:27 UTC, stasatdaglabs commented on domain/kaspadstate/algorithms/ghostdagmanager/ghostdagmanager.go
> +func (gm *GHOSTDAGManager) GHOSTDAG(blockParents []*daghash.Hash) *model.BlockGHOSTDAGData {
I don't want to save its data, though.

2020-10-04 10:31 UTC, stasatdaglabs commented on domain/kaspadstate/algorithms/interfaces.go
> +	BuildBlock(transactionSelector model.TransactionSelector) *appmessage.MsgBlock
This is the external API. You're thinking of the internal buildBlock.

2020-10-05 07:19 UTC, someone235 commented on domain/kaspadstate/datastructures/blockstatusstore/blockstatusstore.go
> +// BlockStatusStore ...
Real comments are still missing

2020-10-05 07:23 UTC, svarogg reviewed
1. Didn't we say we rename "algorithms" to "processes"?
2. Please complete all the comments. Comment is like spec for the implementer. Otherwise we are going to get misunderstandings regarding what people should implement.
3. Please fill-in the fields of the models. Otherwise it will be impossible to implement some of the processes"

2020-10-05 07:23 UTC, svarogg commented on domain/kaspadstate/algorithms/interfaces.go
> +	ValidateBodyInContext(block *appmessage.MsgBlock) error
You are missing ValidateWithUTXO

2020-10-05 07:23 UTC, svarogg commented on domain/miningmanager/blocktemplatebuilder/blocktemplatebuilder.go
> +func (btb *BlockTemplateBuilder) GetBlockTemplate() *appmessage.MsgBlock {
Should receive `scriptPubKey []byte, extraData []byte` as discussed

2020-10-05 14:12 UTC, svarogg requested changes
1. How do we handle notifications?
2. (I think this one we want to defer to closer to Pruning implementation, but writing down just-in-case): For Pruning we'll need some xxxDataStore.DeleteBlabla() methods.

2020-10-05 14:12 UTC, svarogg commented on domain/consensus/processes/interfaces.go
> +	CalculateConsensusStateChanges(block *appmessage.MsgBlock) *model.ConsensusStateChanges
Please add ResolveFinalityConflict(finalityBlockHash) both here and ExternalAPI

2020-10-06 06:35 UTC, svarogg requested changes

2020-10-06 06:35 UTC, svarogg commented on domain/consensus/processes/interfaces.go
> +	BlockAtDepth(uint64) *daghash.Hash
Should also receive block hash

2020-10-06 07:00 UTC, svarogg requested changes

2020-10-06 07:07 UTC, svarogg approved these changes

2020-10-06 07:19 UTC, someone235 requested changes

2020-10-06 07:19 UTC, someone235 commented on domain/consensus/model/reachabilitychangeset.go
> +	treeNodeChanges          map[*daghash.Hash]*reachabilityTreeNode
all fields should be public, no?

2020-10-06 07:19 UTC, someone235 commented on domain/consensus/model/reachabilitydata.go
> +	treeNode          *reachabilityTreeNode
all fields should be public, no?

2020-10-06 07:19 UTC, someone235 commented on domain/consensus/model/reachabilitydata.go
> +	children []*reachabilityTreeNode
all fields should be public, no?

2020-10-06 07:19 UTC, someone235 commented on domain/consensus/model/reachabilitydata.go
> +	start uint64
all fields should be public, no?

2020-10-06 07:19 UTC, someone235 commented on domain/consensus/model/reachabilitydata.go
> +type orderedTreeNodeSet []*reachabilityTreeNode
the type should be public, no?

2020-10-06 07:19 UTC, someone235 commented on domain/consensus/model/reachabilitydata.go
> +type futureCoveringTreeNodeSet orderedTreeNodeSet
the type should be public, no?

2020-10-06 07:19 UTC, someone235 commented on domain/consensus/model/readonlyutxoset.go
>  	Get() (outpoint *appmessage.Outpoint, utxoEntry *UTXOEntry)
I would expect it'll be called `Value`

2020-10-06 07:19 UTC, someone235 commented on domain/consensus/model/selectedparentiterator.go
> +	Get() *daghash.Hash
Here too

2020-10-06 07:19 UTC, someone235 commented on domain/consensus/model/utxodiff.go
> +type utxoCollection map[appmessage.Outpoint]*UTXOEntry
it should be public

2020-10-06 07:19 UTC, someone235 commented on domain/consensus/model/utxoentry.go
> +	amount          uint64
all fields should be public.

2020-10-06 07:28 UTC, someone235 approved these changes

2020-10-06 07:33 UTC, svarogg approved these changes

2020-10-06 07:34 UTC, merged