[NOD-1422] Implement GHOSTDAG
kaspanet/kaspad pull request #950
Opened 2020-10-11 14:25 UTC by someone235

2020-10-12 09:15 UTC, elichai reviewed
The algorithm looks correct and matches what is correctly implemented in 0.7.2-dev

2020-10-12 09:38 UTC, someone235 commented on domain/consensus/processes/ghostdagmanager/ghostdag.go
> +	newBlockData.BlueScore = gm.ghostdagDataStore.Get(gm.databaseContext, newBlockData.SelectedParent).BlueScore +
After block is validated in another process

2020-10-12 09:44 UTC, someone235 commented on domain/consensus/processes/ghostdagmanager/mergeset.go
> +		mergeSetMap[*parent] = struct{}{}
Maybe later on we can try to optimize it by using a shorter internal unique ID per block, but for now it feels like a premature optimization

2020-10-12 09:45 UTC, someone235 commented on domain/consensus/processes/ghostdagmanager/ghostdag.go
> +		BluesAnticoneSizes: make(map[model.DomainHash]model.KType),
I decided not to preallocate here and in MergeSetBlues, because go's GC doesn't ever resize it

2020-10-12 11:16 UTC, elichai approved these changes

2020-10-14 13:39 UTC, stasatdaglabs requested changes

2020-10-14 13:39 UTC, stasatdaglabs commented on domain/consensus/processes/ghostdagmanager/mergeset.go
> +	mergeSetMap := make(map[model.DomainHash]struct{}, gm.k)
Consider renaming this to just mergeSet.

2020-10-14 13:44 UTC, stasatdaglabs approved these changes

2020-10-14 13:47 UTC, merged