[NOD-1464] difficulty refactoring
kaspanet/kaspad pull request #986
Opened 2020-10-29 17:20 UTC by elichai

This still misses params for the constructor (See `//FIXME`)

2020-11-01 13:10 UTC, stasatdaglabs requested changes

2020-11-01 13:10 UTC, stasatdaglabs commented on domain/consensus/processes/difficultymanager/blockwindow.go
> +func (dm *difficultyManager) blueBlockWindow(startingNode *externalapi.DomainHash, windowSize uint64) (blockWindow, error) {
Please use DAGTraversal.BlueWindow instead.

2020-11-01 15:39 UTC, elichai commented on domain/consensus/processes/difficultymanager/blockwindow.go
> +func (dm *difficultyManager) blueBlockWindow(startingNode *externalapi.DomainHash, windowSize uint64) (blockWindow, error) {
Ha!

2020-11-04 09:33 UTC, stasatdaglabs approved these changes

2020-11-04 09:35 UTC, merged